name: Live Bitcoin Price Tracker

# --- TRIGGERS ---
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  fetch-and-save-price:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the repository's code.
      # We need to provide a token here so the checkout action can use it later.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Install the 'jq' tool.
      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0

      # Step 3: Fetch the current Bitcoin price.
      - name: Fetch Bitcoin price
        id: fetch_price
        run: |
          PRICE=$(curl -s 'https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd' | jq -r '.bitcoin.usd')
          if [ -z "$PRICE" ] || [ "$PRICE" == "null" ]; then
            echo "Failed to fetch Bitcoin price. Exiting."
            exit 1
          fi
          echo "price=$PRICE" >> $GITHUB_OUTPUT
          echo "Current BTC Price: $PRICE"

      # Step 4: Update the price history file.
      - name: Update price history file
        run: |
          HISTORY_FILE="price_history.json"
          NEW_PRICE=${{ steps.fetch_price.outputs.price }}
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          if [ -f "$HISTORY_FILE" ]; then
            jq --argjson price "$NEW_PRICE" --arg time "$TIMESTAMP" \
            '.history += [{"price": $price, "timestamp": $time}]' \
            "$HISTORY_FILE" > tmp_history.json && mv tmp_history.json "$HISTORY_FILE"
          else
            jq -n --argjson price "$NEW_PRICE" --arg time "$TIMESTAMP" \
            '{initialPrice: $price, history: [{"price": $price, "timestamp": $time}]}' \
            > "$HISTORY_FILE"
          fi
          echo "Updated price history file."

      # Step 5: Use a dedicated Action to commit the changes.
      # This is more robust than running git commands manually.
      - name: Commit updated price history
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Bitcoin price history"
          file_pattern: price_history.json
